site_name: Bypassing Censorship Guide
site_url: https://mrxehmad.github.io/Bypassing-Censorship-Guide/
theme:
  name: material

nav:
  - Home: index.md
  - Bypassing Censorship:
      - VPNs: 01-Bypassing-Censorship/01-VPNs.md
      - Tor: 01-Bypassing-Censorship/02-Tor.md
      - Proxies: 01-Bypassing-Censorship/03-Proxies.md
  - Privacy Protection:
      - Secure Messengers: 02-Privacy-Protection/01-Secure-Messengers.md
      - Email Encryption: 02-Privacy-Protection/02-Email-Encryption.md
  - Country-Specific Info:
      - Region A: 03-Country-Specific-Info/01-Region-A.md
      - Region B: 03-Country-Specific-Info/02-Region-B.md

docs_dir: page
